-- 코드를 입력하세요
# SELECT CAR_ID, 
#     CASE
#         WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN "대여중"
#         ELSE "대여 가능"
#     END
#     AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE HISTORY_ID IN (SELECT A.HISTORY_ID
#        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
#         GROUP BY A.CAR_ID
#        ORDER BY A.START_DATE DESC            
# )
# GROUP BY CAR_ID
# ORDER BY CAR_ID DESC

SELECT 
    CAR_ID,
    CASE 
        WHEN SUM(
            CASE 
                WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE 
                THEN 1 ELSE 0 
            END
        ) > 0 THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;
